create table blog (
    id integer generated by default as identity (start with 1),
    title varchar(70) not null,
    subtitle varchar(250) not null,
    stringId varchar(30) not null,
    owner_id integer not null,
    primary key (id)
);

create table post (
    id integer generated by default as identity (start with 1),
    date timestamp not null,
    title varchar(150) not null,
    commentsAllowed bit not null,
    draft bit not null,
    content longvarchar,
    blog_id integer not null,
    primary key (id)
);

create table user (
    id integer generated by default as identity (start with 1),
    login varchar(30) not null,
    password varchar(40) not null,
    name varchar(50) not null,
    email varchar(50) not null,
    administrator bit not null,
    primary key (id)
);

alter table blog 
    add constraint blog__owner_id 
    foreign key (owner_id) 
    references user;

alter table post 
    add constraint post__blog_id 
    foreign key (blog_id) 
    references blog;
